spring:
  application:
    name: SkyRush
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/SkyRush
    username: SkyRush
    password: 123
  sql:
    init:
      mode: always
jwt:
  secret: "juda_uzun_va_maxfiy_kalit_shu_yerda_bolishi_shart_32_belgi"
  expiration: 86400000 # 24 soat (ms da)